In [49]:
import pandas as pd

In [50]:
df=pd.read_csv("medical_insurance.csv")
df

     Age    BMI  Children  Smoker  ExerciseHours  InsuranceCost
0     56  25.09         5       1              3       45806.79
1     46  35.82         4       0              1       35906.20
2     32  23.60         2       0              2       24443.55
3     60  32.99         5       0              2       36754.28
4     25  34.73         1       0              4       16910.70
..   ...    ...       ...     ...            ...            ...
995   22  27.51         0       0              3       17019.04
996   40  24.86         4       1              0       40261.02
997   27  29.14         1       0              3       18094.49
998   61  27.67         4       0              4       30173.25
999   19  20.32         4       0              4       15182.53

[1000 rows x 6 columns]

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            1000 non-null   int64
 1   BMI            1000 non-null   float64
 2   Children       1000 non-null   int64
 3   Smoker         1000 non-null   int64
 4   ExerciseHours  1000 non-null   int64
 5   InsuranceCost  1000 non-null   float64
dtypes: float64(2), int64(4)
memory usage: 47.0 KB

In [52]:
df.isnull().sum()

Age              0
BMI              0
Children         0
Smoker           0
ExerciseHours    0
InsuranceCost    0
dtype: int64

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            1000 non-null   int64
 1   BMI            1000 non-null   float64
 2   Children       1000 non-null   int64
 3   Smoker         1000 non-null   int64
 4   ExerciseHours  1000 non-null   int64
 5   InsuranceCost  1000 non-null   float64
dtypes: float64(2), int64(4)
memory usage: 47.0 KB

In [54]:
df.describe()

,Age,BMI,Children,Smoker,ExerciseHours,InsuranceCost
count,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000
mean,40.986000,29.101780,2.547000,0.49000,2.513000,34653.106860
std,13.497852,6.403871,1.708423,0.50015,1.714284,9644.011989
min,18.000000,18.100000,0.000000,0.00000,0.000000,8923.000000
25%,29.000000,23.247500,1.000000,0.00000,1.000000,27583.435000
50%,42.000000,29.340000,3.000000,0.00000,2.000000,34666.895000
75%,52.000000,34.650000,4.000000,1.00000,4.000000,41926.820000
max,64.000000,39.990000,5.000000,1.00000,5.000000,56753.150000

In [55]:
df.duplicated().sum()

np.int64(0)

In [56]:
df.drop_duplicates(inplace=True)

In [57]:
x=df.drop(['InsuranceCost'],axis=1)

In [58]:
y=df['InsuranceCost']
y

0      45806.79
1      35906.20
2      24443.55
3      36754.28
4      16910.70
         ...
995    17019.04
996    40261.02
997    18094.49
998    30173.25
999    15182.53
Name: InsuranceCost, Length: 1000, dtype: float64

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2,
                                               random_state=42
                                               )

In [61]:
#from sklearn.tree import DecisionTreeRegressor#score:0.787691
#from sklearn.ensemble import RandomForestRegressor #score:0.8940
from sklearn.linear_model import LinearRegression #SCORE:0.9053
model=LinearRegression()

In [62]:
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9033449974233129

In [63]:
import pickle
with open('medical_insurance.pkl','wb') as f:
    pickle.dump(model,f)